app = "lua-server"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080

[[services]]
  internal_port = 9000
  protocol = "tcp"

  [[services.ports]]
    port = 9000
